plugins {
    id 'java'
    id 'idea'
    id 'application'
    id 'distribution'
    id 'org.beryx.runtime' version '2.0.1'
}

repositories {
    gradlePluginPortal()
    mavenLocal()
    mavenCentral()
    maven { url = "https://www.jetbrains.com/intellij-repository/releases" }
    maven { url = "https://cache-redirector.jetbrains.com/intellij-dependencies" }
    maven { url = "https://oss.sonatype.org/content/repositories/snapshots" }
}

group = 'net.rptools'
version = '0.beta'

application {
    mainClass = 'net.rptools.Main'
    applicationName = 'HandlebarsTool'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

def cache2kVersion = '2.6.1.Final'
dependencies {
    implementation("org.beryx.runtime:org.beryx.runtime.gradle.plugin:2.0.1")
//    implementation 'org.beryx:badass-jlink-plugin:3.1.5'
    implementation 'com.github.jknack:handlebars:4.5.0'
    implementation 'com.github.jknack:handlebars-helpers:4.5.0'
    implementation 'com.github.jknack:handlebars-jackson2:4.3.1'

    implementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'


    implementation "org.cache2k:cache2k-api:${cache2kVersion}"
    runtimeOnly "org.cache2k:cache2k-core:${cache2kVersion}"
    implementation 'com.jayway.jsonpath:json-path:2.10.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.1'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.20.1'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.20.2'
    implementation 'commons-io:commons-io:2.21.0'

    implementation 'org.eclipse.jetty:jetty-webapp:11.0.26'
    implementation 'org.eclipse.jetty:jetty-server:12.1.5'
    implementation 'org.eclipse.jetty.ee10:jetty-ee10-servlet:12.1.5'
    implementation 'org.eclipse.jetty:jetty-servlets:11.0.26'

    implementation 'org.jsoup:jsoup:1.21.2'

    implementation 'com.jetbrains.intellij.java:java-gui-forms-rt:241.12019'
//    antTask 'com.jetbrains.intellij.java:java-compiler-ant-tasks:233.14475.56'

    implementation 'org.apache.logging.log4j:log4j-core:2.25.3'
    implementation 'org.apache.logging.log4j:log4j-api:2.25.3'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.25.3'
    implementation 'org.slf4j:slf4j-api:2.0.17'
}
jar {
    destinationDirectory.set(file("$projectDir/out/libs"))
    manifest {
        attributes 'Main-Class': 'net.rptools.Main'
    }
}
tasks.register('createWrapper', Wrapper) {
    gradleVersion = '9.2.1'
}

runtime {
    javaHome = 'C:/Users/Strat/.jdks/corretto-24.0.2/'
    options = ['--strip-native-commands',
               '--strip-debug',
               '--compress',
               '2',
               '--no-header-files',
               '--no-man-pages'
    ]

// Uncomment and adjust the code below if you want to generate images for multiple platforms.
// (You need to also uncomment the line 'targetPlatformName = ...' in the jpackage block.)

//    targetPlatform("lin") {
//        jdkHome = jdkDownload("https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz")
//    }
//
//    targetPlatform("mac") {
//        jdkHome = jdkDownload("https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_mac_hotspot_15.0.2_7.tar.gz") {
//            downloadDir = "$buildDir/mac"
//            archiveName = "mac-jdk"
//            archiveExtension = "tar.gz"
//            pathToHome = "jdk-15.0.2+7/Contents/Home"
//            overwrite = true
//        }
//    }

    targetPlatform("win") {
        jdkHome = jdkDownload("https://corretto.aws/downloads/latest/amazon-corretto-25-x64-windows-jdk.zip")
    }


    launcher {
        noConsole = true
    }
    jpackage {
        // Uncomment and adjust the following line if your runtime task is configured to generate images for multiple platforms
        targetPlatformName = "win"

        def currentOs = org.gradle.internal.os.OperatingSystem.current()
        def imgType = currentOs.windows ? 'ico' : currentOs.macOsX ? 'icns' : 'png'
        imageOptions += ['--icon', "src/main/resources/testPage/favicon.$imgType"]
        installerOptions += ['--resource-dir', "src/main/resources"]
        installerOptions += ['--vendor', 'Reverend']
        installerOptions += ['--type', 'app-image']
        installerOptions += ['--app-version', version]
        installerOptions += ['--dest', "runtime"]
        installerOptions += ['--copyright', "©2026 Jay Stratton"]
        installerOptions += ['--description', "Tool for developing Handlebars Templates."]
        installerOptions += ['--name', "HandlebarsTool"]
        installerOptions += ['--jlink-options', options]

        if(currentOs.windows) {
            installerOptions += ['--win-per-user-install', '--win-dir-chooser', '--win-menu', '--win-shortcut']
        }
//        else if (currentOs.linux) {
//            installerOptions += ['--linux-package-name', 'HandlebarsTool','--linux-shortcut']
//        }
//        else if (currentOs.macOsX) {
//            installerOptions += ['--mac-package-name', 'HandlebarsTool']
//        }
    }
    tasks.jpackage.doFirst {
        def currentOs = org.gradle.internal.os.OperatingSystem.current()
        def basePath = currentOs.windows ? project.name : currentOs.linux ? "$project.name/lib" : "${project.name}.app/Contents"
        def folder = project(':myProject').file('src/main/resources/')
        copy {
            from(folder)
            into("$projectDir/build/jpackage/$basePath/app")
        }
    }
}